### ISSUE TITLE
Swift support ?

### ISSUE THREAD

**Issue by havocked** [appstud/Azot#2]
How can we implement it in a swift project ?

**Comment by RemyMrt** [comment]
Hello @havocked,

You can use cocoa pod and include Azot through your bridging header as other objectiveC libraries.

Check out this link for more informations about bridging headers in swift: 

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

Cheers,

Remy

**Comment by atnpem** [comment]
I had the same problem :s Can you add demo code in the doc ?

Thx bro

**Comment by havocked** [comment]
Hi,

Really bad support here, you should actually help Swift community (even beginners) with some steps or code sample, not just linking a website...

If you want I can open a issue on StackOverflow perhaps it would be more appropriate ?
